/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vent;

/**
 *
 * @author admin
 */
public class Agregar_Usuario extends javax.swing.JFrame {

    /**
     * Creates new form Agregar_Usuario
     */
    public Agregar_Usuario() {
        initComponents();
                this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1Adduser = new javax.swing.JLabel();
        jButton1Regre = new javax.swing.JButton();
        jButton1Regis = new javax.swing.JButton();
        jLabel1UserRe = new javax.swing.JLabel();
        jTextField1RegistraU = new javax.swing.JTextField();
        jLabel1PassRe = new javax.swing.JLabel();
        jTextField1RegistraPass = new javax.swing.JTextField();
        jLabel1VentanaNombr5 = new javax.swing.JLabel();
        jLabel1FondoRe = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1Adduser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMg/adduser_1.png"))); // NOI18N
        getContentPane().add(jLabel1Adduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jButton1Regre.setBackground(new java.awt.Color(255, 153, 0));
        jButton1Regre.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1Regre.setText("Regresar");
        jButton1Regre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1RegreActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Regre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        jButton1Regis.setBackground(new java.awt.Color(0, 153, 204));
        jButton1Regis.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1Regis.setText("Registrar");
        getContentPane().add(jButton1Regis, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel1UserRe.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1UserRe.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1UserRe.setText("Usuario");
        getContentPane().add(jLabel1UserRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jTextField1RegistraU.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(jTextField1RegistraU, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 190, 30));

        jLabel1PassRe.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1PassRe.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1PassRe.setText("Contraseña");
        getContentPane().add(jLabel1PassRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jTextField1RegistraPass.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        getContentPane().add(jTextField1RegistraPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 190, 30));

        jLabel1VentanaNombr5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1VentanaNombr5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1VentanaNombr5.setText("Nuevo Usuario");
        getContentPane().add(jLabel1VentanaNombr5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabel1FondoRe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMg/FondoRe.jpg"))); // NOI18N
        getContentPane().add(jLabel1FondoRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 247, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1RegreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1RegreActionPerformed
        // TODO add your handling code here:
        
                
        Login pro = new Login();
        pro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1RegreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Regis;
    private javax.swing.JButton jButton1Regre;
    private javax.swing.JLabel jLabel1Adduser;
    private javax.swing.JLabel jLabel1FondoRe;
    private javax.swing.JLabel jLabel1PassRe;
    private javax.swing.JLabel jLabel1UserRe;
    private javax.swing.JLabel jLabel1VentanaNombr5;
    private javax.swing.JTextField jTextField1RegistraPass;
    private javax.swing.JTextField jTextField1RegistraU;
    // End of variables declaration//GEN-END:variables
}
