/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vent;

/**
 *
 * @author admin
 */
public class Regis_Cat extends javax.swing.JFrame {

    /**
     * Creates new form Regis_Cat
     */
    public Regis_Cat() {
        initComponents();
                this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1ImgCat = new javax.swing.JLabel();
        jButton1Regresar3 = new javax.swing.JButton();
        jButton1Regis3 = new javax.swing.JButton();
        jTextField1DescriCa = new javax.swing.JTextField();
        jLabel1DescriCat = new javax.swing.JLabel();
        jLabel1NombreCat = new javax.swing.JLabel();
        jTextField1NombreCat = new javax.swing.JTextField();
        jButton1Actualizar = new javax.swing.JButton();
        jButton1Regis4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1CATEGORIA = new javax.swing.JTable();
        jLabel1VentanaNombre = new javax.swing.JLabel();
        jLabel1FondoCat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1ImgCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMg/Categoria.png"))); // NOI18N
        getContentPane().add(jLabel1ImgCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jButton1Regresar3.setBackground(new java.awt.Color(255, 153, 0));
        jButton1Regresar3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1Regresar3.setText("Regresar");
        jButton1Regresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1Regresar3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1Regresar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, -1, -1));

        jButton1Regis3.setBackground(new java.awt.Color(0, 153, 204));
        jButton1Regis3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1Regis3.setText("Registrar");
        getContentPane().add(jButton1Regis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 110, -1));
        getContentPane().add(jTextField1DescriCa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, 30));

        jLabel1DescriCat.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1DescriCat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1DescriCat.setText("Descripción");
        getContentPane().add(jLabel1DescriCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel1NombreCat.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1NombreCat.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1NombreCat.setText("Nombre");
        getContentPane().add(jLabel1NombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        getContentPane().add(jTextField1NombreCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 170, 30));

        jButton1Actualizar.setBackground(new java.awt.Color(153, 153, 255));
        jButton1Actualizar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1Actualizar.setText("Actualizar");
        getContentPane().add(jButton1Actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, -1, -1));

        jButton1Regis4.setBackground(new java.awt.Color(255, 51, 51));
        jButton1Regis4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jButton1Regis4.setText("Eliminar");
        getContentPane().add(jButton1Regis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 110, -1));

        jTable1CATEGORIA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1CATEGORIA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 330, 90));

        jLabel1VentanaNombre.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1VentanaNombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1VentanaNombre.setText("Ingreso de Categoría");
        getContentPane().add(jLabel1VentanaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel1FondoCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMg/Regist_Cat.jpg"))); // NOI18N
        getContentPane().add(jLabel1FondoCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1Regresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1Regresar3ActionPerformed
        // TODO add your handling code here:
        
        //Pasar Vnetana al menu
                
        Menu pro = new Menu();
        pro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1Regresar3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regis_Cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regis_Cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regis_Cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regis_Cat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regis_Cat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Actualizar;
    private javax.swing.JButton jButton1Regis3;
    private javax.swing.JButton jButton1Regis4;
    private javax.swing.JButton jButton1Regresar3;
    private javax.swing.JLabel jLabel1DescriCat;
    private javax.swing.JLabel jLabel1FondoCat;
    private javax.swing.JLabel jLabel1ImgCat;
    private javax.swing.JLabel jLabel1NombreCat;
    private javax.swing.JLabel jLabel1VentanaNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1CATEGORIA;
    private javax.swing.JTextField jTextField1DescriCa;
    private javax.swing.JTextField jTextField1NombreCat;
    // End of variables declaration//GEN-END:variables
}
